"""create locations

Revision ID: 2134a61d3ac1
Revises: c0a888f3aae4
Create Date: 2026-09-21 15:30:04.141837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134a61d3ac1'
down_revision: Union[str, Sequence[str], None] = 'c0a888f3aae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stanox', sa.Text(), nullable=True),
    sa.Column('uic', sa.Text(), nullable=True),
    sa.Column('three_alpha', sa.Text(), nullable=True),
    sa.Column('tiploc', sa.Text(), nullable=True),
    sa.Column('nlc', sa.Text(), nullable=True),
    sa.Column('nlc_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_stanox'), 'locations', ['stanox'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_stanox'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
