"""update locations unique constraint

Revision ID: 77eb5a52e4a3
Revises: 2134a61d3ac1
Create Date: 2026-09-21 16:29:55.804693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77eb5a52e4a3'
down_revision: Union[str, Sequence[str], None] = '2134a61d3ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_stanox'), table_name='locations')
    op.create_index(op.f('ix_locations_tiploc'), 'locations', ['tiploc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_tiploc'), table_name='locations')
    op.create_index(op.f('ix_locations_stanox'), 'locations', ['stanox'], unique=True)
    # ### end Alembic commands ###
